CREATE TABLE [stg].[Technician_Reports](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Technician] VARCHAR(MAX) NULL,
	[Hours Logged] VARCHAR(MAX) NULL,
	[Total Melds Completed] VARCHAR(MAX) NULL,
	[For Rent Sign completed] VARCHAR(MAX) NULL,
	[Evaluation completed] VARCHAR(MAX) NULL,
	[Turnover completed] VARCHAR(MAX) NULL,
	[Appliances completed] VARCHAR(MAX) NULL,
	[Blinds/Window treatments completed] VARCHAR(MAX) NULL,
	[Circuit Breaker completed] VARCHAR(MAX) NULL,
	[Cleaning completed] VARCHAR(MAX) NULL,
	[Doors completed] VARCHAR(MAX) NULL,
	[Driveway completed] VARCHAR(MAX) NULL,
	[Drywall completed] VARCHAR(MAX) NULL,
	[Electrical completed] VARCHAR(MAX) NULL,
	[Exterior completed] VARCHAR(MAX) NULL,
	[Fireplace completed] VARCHAR(MAX) NULL,
	[Flooring completed] VARCHAR(MAX) NULL,
	[Garage Door completed] VARCHAR(MAX) NULL,
	[Garbage Disposal completed] VARCHAR(MAX) NULL,
	[General completed] VARCHAR(MAX) NULL,
	[Hardware completed] VARCHAR(MAX) NULL,
	[Heating/AC completed] VARCHAR(MAX) NULL,
	[Interior completed] VARCHAR(MAX) NULL,
	[Landscaping completed] VARCHAR(MAX) NULL,
	[Locks completed] VARCHAR(MAX) NULL,
	[Other completed] VARCHAR(MAX) NULL,
	[Painting completed] VARCHAR(MAX) NULL,
	[Outside Water Spigot completed] VARCHAR(MAX) NULL,
	[Pest control completed] VARCHAR(MAX) NULL,
	[Plumbing completed] VARCHAR(MAX) NULL,
	[Carpentry completed] VARCHAR(MAX) NULL,
	[Pool completed] VARCHAR(MAX) NULL,
	[Roofing completed] VARCHAR(MAX) NULL,
	[Sewer completed] VARCHAR(MAX) NULL,
	[Shower completed] VARCHAR(MAX) NULL,
	[Siding completed] VARCHAR(MAX) NULL,
	[Smoke Detector/CO detectors completed] VARCHAR(MAX) NULL,
	[Soffit/Fascia completed] VARCHAR(MAX) NULL,
	[Stairs completed] VARCHAR(MAX) NULL,
	[Toilet completed] VARCHAR(MAX) NULL,
	[Towel bars completed] VARCHAR(MAX) NULL,
	[Violations completed] VARCHAR(MAX) NULL,
	[Washer/Dryer completed] VARCHAR(MAX) NULL,
	[Water Damage completed] VARCHAR(MAX) NULL,
	[Water Heater completed] VARCHAR(MAX) NULL,
	[Water Softener completed] VARCHAR(MAX) NULL,
	[Windows completed] VARCHAR(MAX) NULL,
	[For Rent Sign logged] VARCHAR(MAX) NULL,
	[Evaluation logged] VARCHAR(MAX) NULL,
	[Turnover logged] VARCHAR(MAX) NULL,
	[Appliances logged] VARCHAR(MAX) NULL,
	[Blinds/Window treatments logged] VARCHAR(MAX) NULL,
	[Circuit Breaker logged] VARCHAR(MAX) NULL,
	[Cleaning logged] VARCHAR(MAX) NULL,
	[Doors logged] VARCHAR(MAX) NULL,
	[Driveway logged] VARCHAR(MAX) NULL,
	[Drywall logged] VARCHAR(MAX) NULL,
	[Electrical logged] VARCHAR(MAX) NULL,
	[Exterior logged] VARCHAR(MAX) NULL,
	[Fireplace logged] VARCHAR(MAX) NULL,
	[Flooring logged] VARCHAR(MAX) NULL,
	[Garage Door logged] VARCHAR(MAX) NULL,
	[Garbage Disposal logged] VARCHAR(MAX) NULL,
	[General logged] VARCHAR(MAX) NULL,
	[Hardware logged] VARCHAR(MAX) NULL,
	[Heating/AC logged] VARCHAR(MAX) NULL,
	[Interior logged] VARCHAR(MAX) NULL,
	[Landscaping logged] VARCHAR(MAX) NULL,
	[Locks logged] VARCHAR(MAX) NULL,
	[Other logged] VARCHAR(MAX) NULL,
	[Painting logged] VARCHAR(MAX) NULL,
	[Outside Water Spigot logged] VARCHAR(MAX) NULL,
	[Pest control logged] VARCHAR(MAX) NULL,
	[Plumbing logged] VARCHAR(MAX) NULL,
	[Carpentry logged] VARCHAR(MAX) NULL,
	[Pool logged] VARCHAR(MAX) NULL,
	[Roofing logged] VARCHAR(MAX) NULL,
	[Sewer logged] VARCHAR(MAX) NULL,
	[Shower logged] VARCHAR(MAX) NULL,
	[Siding logged] VARCHAR(MAX) NULL,
	[Smoke Detector/CO detectors logged] VARCHAR(MAX) NULL,
	[Soffit/Fascia logged] VARCHAR(MAX) NULL,
	[Stairs logged] VARCHAR(MAX) NULL,
	[Toilet logged] VARCHAR(MAX) NULL,
	[Towel bars logged] VARCHAR(MAX) NULL,
	[Violations logged] VARCHAR(MAX) NULL,
	[Washer/Dryer logged] VARCHAR(MAX) NULL,
	[Water Damage logged] VARCHAR(MAX) NULL,
	[Water Heater logged] VARCHAR(MAX) NULL,
	[Water Softener logged] VARCHAR(MAX) NULL,
	[Windows logged] VARCHAR(MAX) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

