/*
TRUNCATE TABLE [stg].[Owners_Reports]
TRUNCATE TABLE [dbo].[Owners_Reports]
TRUNCATE TABLE [stg].[Tenants_Reports]
TRUNCATE TABLE [dbo].[Tenants_Reports]
TRUNCATE TABLE [stg].[Melds_Reports]
TRUNCATE TABLE [dbo].[Melds_Reports]
TRUNCATE TABLE [stg].[Expenditures_Reports]
TRUNCATE TABLE [dbo].[Expenditures_Reports]
TRUNCATE TABLE [stg].[Detailed_Expenditures_Reports]
TRUNCATE TABLE [dbo].[Detailed_Expenditures_Reports]
TRUNCATE TABLE [stg].[Invoices_Reports] 
TRUNCATE TABLE [dbo].[Invoices_Reports] 
TRUNCATE TABLE [stg].[Technician_Reports]
TRUNCATE TABLE [dbo].[Technician_Reports]
TRUNCATE TABLE [stg].[Units_Reports]
TRUNCATE TABLE [dbo].[Units_Reports]
TRUNCATE TABLE [stg].[Work_Logs_Reports]
TRUNCATE TABLE [dbo].[Work_Logs_Reports]

SELECT * FROM  [stg].[Owners_Reports]
SELECT * FROM  [stg].[Tenants_Reports]
SELECT * FROM  [stg].[Melds_Reports] 
SELECT * FROM  [stg].[Expenditures_Reports]
SELECT * FROM  [stg].[Detailed_Expenditures_Reports]
SELECT * FROM  [stg].[Invoices_Reports] 
SELECT * FROM  [stg].[Technician_Reports]
SELECT * FROM  [stg].[Units_Reports]
SELECT * FROM  [stg].[Work_Logs_Reports]

*/
SELECT * FROM  [dbo].[Owners_Reports]
SELECT * FROM  [dbo].[Tenants_Reports]
SELECT * FROM  [dbo].[Melds_Reports]
SELECT * FROM  [dbo].[Expenditures_Reports]
SELECT * FROM  [dbo].[Detailed_Expenditures_Reports] 

SELECT * FROM  [dbo].[Invoices_Reports] 
SELECT * FROM  [dbo].[Technician_Reports]
SELECT * FROM  [dbo].[Units_Reports]
SELECT * FROM  [dbo].[Work_Logs_Reports]
